---
title: "Tp_movilidad_cdde2"
author: "Lucas S. Melfi"
date: "2025-05-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Librerías}
library(tidyverse)
library(here)
library(sf)
library(nngeo)

```
```{r Carga de datos}

url_bsasdata <- "https://cdn.buenosaires.gob.ar/datosabiertos/datasets/transporte-y-obras-publicas"
url_premetro <- "https://cdn.buenosaires.gob.ar//datosabiertos/datasets/sbase/premetro"

#Comunas
comunas_caba <- st_read("https://cdn.buenosaires.gob.ar/datosabiertos/datasets/ministerio-de-educacion/comunas/comunas.geojson")

#Premetro
lineas_pre <- st_read(paste(url_premetro, "lineas_de_premetro.geojson", 
                      sep = "/") )
est_pre <- st_read(paste(url_premetro, "estaciones-premetro.csv", sep = "/"),
                   options = "GEOM_POSSIBLE_NAMES=geometry",
                   crs = 4326)

reco_pre <- st_read(paste(url_premetro, "recorrido-premetro.csv", sep = "/"),
                   options = "GEOM_POSSIBLE_NAMES=WKT",
                   crs = 4326)
#Subte
frec_sub <- read.csv2 (paste(url_bsasdata,
                   "frecuencia-subte","frecuencia_subte.csv",
                   sep = "/" ) ) 

est_sub <-  st_read(dsn = "https://cdn.buenosaires.gob.ar/datosabiertos/datasets/sbase/subte-estaciones/estaciones-de-subte.geojson")
                    
bocas_sub <- st_read(dsn = "https://cdn.buenosaires.gob.ar/datosabiertos/datasets/sbase/bocas-subte/bocas-de-subte.geojson") |> 
  select(-matches("lineas_de_"))




  
         


```

